import type { Lesson, VocabularyItem } from "@/lib/types";

const vocabularyBase: VocabularyItem[] = [
  {
    id: "alltag-termin",
    topic: "Termine",
    german: "der Termin",
    russian: "встреча, запись",
    exampleSentence: "Ich habe morgen einen Termin beim Bürgeramt.",
    difficulty: "A2",
  },
  {
    id: "alltag-puenktlich",
    topic: "Alltag",
    german: "pünktlich",
    russian: "пунктуально",
    exampleSentence: "Zur Prüfung komme ich pünktlich.",
    difficulty: "A2",
  },
  {
    id: "wohnen-miete",
    topic: "Wohnen",
    german: "die Miete",
    russian: "арендная плата",
    exampleSentence: "Die Miete ist seit Januar höher.",
    difficulty: "A2",
  },
  {
    id: "arbeit-arbeitgeber",
    topic: "Arbeit",
    german: "der Arbeitgeber",
    russian: "работодатель",
    exampleSentence: "Mein Arbeitgeber bezahlt den Deutschkurs.",
    difficulty: "B1",
  },
  {
    id: "pruefung-aufgabe",
    topic: "Prüfung",
    german: "die Aufgabe",
    russian: "задание",
    exampleSentence: "Bitte lesen Sie die Aufgabe genau.",
    difficulty: "A2",
  },
  {
    id: "familie-erlebnis",
    topic: "Familie",
    german: "das Erlebnis",
    russian: "событие, впечатление",
    exampleSentence: "Ich berichte in der Prüfung über ein persönliches Erlebnis.",
    difficulty: "B1",
  },
  {
    id: "freizeit-handy",
    topic: "Freizeit",
    german: "das Handy",
    russian: "мобильный телефон",
    exampleSentence: "Viele Kinder möchten früh ein eigenes Handy haben.",
    difficulty: "B1",
  },
  {
    id: "reisen-unterkunft",
    topic: "Reisen",
    german: "die Unterkunft",
    russian: "жилье на время поездки",
    exampleSentence: "Für den Urlaub suchen wir eine günstige Unterkunft.",
    difficulty: "B1",
  },
  {
    id: "pruefung-bestehen",
    topic: "Prüfung",
    german: "bestehen",
    russian: "сдать, выдержать",
    exampleSentence: "Ich möchte die B1-Prüfung bestehen.",
    difficulty: "A2",
  },
  {
    id: "pruefung-teil",
    topic: "Prüfung",
    german: "der Teil",
    russian: "часть",
    exampleSentence: "Der mündliche Teil dauert ungefähr 15 Minuten.",
    difficulty: "A2",
  },
  {
    id: "arbeit-bewerbung",
    topic: "Arbeit",
    german: "die Bewerbung",
    russian: "заявка на работу",
    exampleSentence: "Ich habe gestern eine Bewerbung geschickt.",
    difficulty: "B1",
  },
  {
    id: "arbeit-erfahrung",
    topic: "Arbeit",
    german: "die Erfahrung",
    russian: "опыт",
    exampleSentence: "Ich habe Erfahrung im Büro.",
    difficulty: "B1",
  },
  {
    id: "alltag-behoerde",
    topic: "Alltag",
    german: "die Behörde",
    russian: "ведомство, учреждение",
    exampleSentence: "Bei der Behörde muss man oft warten.",
    difficulty: "B1",
  },
  {
    id: "alltag-seit",
    topic: "Alltag",
    german: "seit",
    russian: "с, начиная с",
    exampleSentence: "Ich lerne seit zwei Jahren Deutsch.",
    difficulty: "A2",
  },
  {
    id: "wohnen-umzug",
    topic: "Wohnen",
    german: "der Umzug",
    russian: "переезд",
    exampleSentence: "Nach dem Umzug muss ich mich anmelden.",
    difficulty: "A2",
  },
  {
    id: "wohnen-anmeldung",
    topic: "Wohnen",
    german: "die Anmeldung",
    russian: "регистрация",
    exampleSentence: "Die Anmeldung ist im Bürgeramt möglich.",
    difficulty: "B1",
  },
  {
    id: "termine-verschieben",
    topic: "Termine",
    german: "verschieben",
    russian: "перенести",
    exampleSentence: "Ich muss den Termin leider verschieben.",
    difficulty: "A2",
  },
  {
    id: "termine-bestaetigen",
    topic: "Termine",
    german: "bestätigen",
    russian: "подтвердить",
    exampleSentence: "Können Sie den Termin bitte bestätigen?",
    difficulty: "B1",
  },
  {
    id: "pruefung-meinung",
    topic: "Prüfung",
    german: "die Meinung",
    russian: "мнение",
    exampleSentence: "In der Prüfung soll ich meine Meinung sagen.",
    difficulty: "A2",
  },
  {
    id: "pruefung-begruenden",
    topic: "Prüfung",
    german: "begründen",
    russian: "обосновывать",
    exampleSentence: "Bitte begründen Sie Ihre Meinung.",
    difficulty: "B1",
  },
  {
    id: "alltag-gesundheit",
    topic: "Gesundheit",
    german: "die Gesundheit",
    russian: "здоровье",
    exampleSentence: "Gesundheit ist ein wichtiges Thema im Alltag.",
    difficulty: "A2",
  },
  {
    id: "arbeit-kuendigung",
    topic: "Arbeit",
    german: "die Kündigung",
    russian: "увольнение, расторжение",
    exampleSentence: "Eine Kündigung muss schriftlich sein.",
    difficulty: "B1",
  },
  {
    id: "umwelt-muelltrennung",
    topic: "Umwelt",
    german: "die Mülltrennung",
    russian: "сортировка мусора",
    exampleSentence: "Mülltrennung ist in vielen Städten sehr wichtig.",
    difficulty: "B1",
  },
  {
    id: "gesundheit-unfall",
    topic: "Gesundheit",
    german: "der Unfall",
    russian: "несчастный случай, авария",
    exampleSentence: "Ein Teilnehmer aus dem Kurs hatte einen Unfall.",
    difficulty: "B1",
  },
  {
    id: "wohnen-nachbar",
    topic: "Wohnen",
    german: "der Nachbar",
    russian: "сосед",
    exampleSentence: "Mein Nachbar hilft mir beim Umzug.",
    difficulty: "A2",
  },
  {
    id: "termine-frist",
    topic: "Termine",
    german: "die Frist",
    russian: "срок",
    exampleSentence: "Die Frist endet am Freitag.",
    difficulty: "B1",
  },
];

const wordForms: Record<string, Partial<VocabularyItem>> = {
  "alltag-termin": { plural: "die Termine", construction: "einen Termin vereinbaren / verschieben" },
  "wohnen-miete": { plural: "die Mieten", construction: "die Miete bezahlen" },
  "arbeit-arbeitgeber": { plural: "die Arbeitgeber" }, "pruefung-aufgabe": { plural: "die Aufgaben" },
  "familie-erlebnis": { plural: "die Erlebnisse" }, "freizeit-handy": { plural: "die Handys" },
  "reisen-unterkunft": { plural: "die Unterkünfte", construction: "eine Unterkunft buchen" },
  "pruefung-bestehen": { verbForms: "besteht, bestand, hat bestanden", construction: "eine Prüfung bestehen" },
  "pruefung-teil": { plural: "die Teile" }, "arbeit-bewerbung": { plural: "die Bewerbungen", construction: "sich um eine Stelle bewerben" },
  "arbeit-erfahrung": { plural: "die Erfahrungen", construction: "Erfahrung mit + Dativ" }, "alltag-behoerde": { plural: "die Behörden" },
  "alltag-seit": { construction: "seit + Dativ" }, "wohnen-umzug": { plural: "die Umzüge" }, "wohnen-anmeldung": { plural: "die Anmeldungen" },
  "termine-verschieben": { verbForms: "verschiebt, verschob, hat verschoben", construction: "einen Termin auf + Akkusativ verschieben" },
  "termine-bestaetigen": { verbForms: "bestätigt, bestätigte, hat bestätigt", construction: "einen Termin bestätigen" },
  "pruefung-meinung": { plural: "die Meinungen", construction: "meiner Meinung nach" },
  "pruefung-begruenden": { verbForms: "begründet, begründete, hat begründet", construction: "eine Meinung begründen" },
  "arbeit-kuendigung": { plural: "die Kündigungen" }, "gesundheit-unfall": { plural: "die Unfälle" }, "wohnen-nachbar": { plural: "die Nachbarn" }, "termine-frist": { plural: "die Fristen" },
};
export const vocabulary: VocabularyItem[] = vocabularyBase.map((word) => ({ ...word, ...wordForms[word.id] }));

export const lessons: Lesson[] = [
  {
    id: "fallback-b1-lesson",
    title: "B1 Alltag: Termin verschieben",
    level: "B1",
    topic: "Termine",
    studyDay: 1,
    estimatedMinutes: 35,
    warmUpReview:
      "Fallback-урок используется только если AI-генерация недоступна. Тема: перенести встречу и объяснить причину.",
    vocabularyIds: [
      "alltag-termin",
      "termine-verschieben",
      "termine-bestaetigen",
      "termine-frist",
      "alltag-puenktlich",
      "alltag-gesundheit",
      "pruefung-begruenden",
    ],
    grammar: {
      title: "weil + глагол в конце",
      explanationRu:
        "В B1 важно объяснять причину. После weil спрягаемый глагол стоит в конце: Ich verschiebe den Termin, weil ich krank bin.",
      examples: [
        "Ich kann heute nicht kommen, weil ich krank bin.",
        "Könnten wir den Termin verschieben, weil ich arbeiten muss?",
        "Ich hoffe, dass ein neuer Termin möglich ist.",
      ],
    },
    readingText:
      "Sehr geehrte Frau Schneider, leider kann ich morgen nicht zum Termin kommen, weil ich krank bin. Könnten wir den Termin bitte auf nächste Woche verschieben? Ich bin am Dienstag oder Donnerstag ab 15 Uhr erreichbar. Vielen Dank für Ihr Verständnis.",
    exercises: [
      {
        id: "fallback-1",
        type: "fill-blank",
        promptRu: "Вставьте союз: Ich kann nicht kommen, ___ ich krank bin.",
        sentence: "Ich kann nicht kommen, ___ ich krank bin.",
        answer: "weil",
        explanationRu: "Нужна причина, поэтому используется weil. Глагол в придаточной части стоит в конце.",
      },
      {
        id: "fallback-2",
        type: "translation",
        promptRu: "Переведите: Я хотел бы перенести встречу.",
        answer: "Ich möchte den Termin verschieben.",
        acceptableAnswers: ["Ich würde den Termin gern verschieben."],
        explanationRu: "Termin verschieben = перенести встречу/запись.",
      },
      {
        id: "fallback-3",
        type: "free-writing",
        promptRu: "Напишите короткое письмо: вы не можете прийти и просите новый Termin.",
        answer:
          "Sehr geehrte Damen und Herren, leider kann ich morgen nicht kommen, weil ich krank bin. Könnten wir den Termin bitte verschieben? Vielen Dank.",
        explanationRu: "Проверьте структуру: обращение, причина, просьба, благодарность.",
      },
    ],
    freePromptRu:
      "Напишите B1-E-Mail: вы переносите Termin, объясняете причину и предлагаете два новых времени.",
    speakingPromptDe: "Sie können einen Termin nicht wahrnehmen. Was sagen Sie am Telefon?",
    successCriteria: [
      "Есть причина с weil.",
      "Есть вежливая просьба.",
      "Есть два новых варианта времени.",
      "Письмо понятно без перевода на русский.",
    ],
    source: "fallback",
  },
];

export const vocabularyById = Object.fromEntries(
  vocabulary.map((item) => [item.id, item]),
) as Record<string, VocabularyItem>;
