"use client";
import { useState } from "react";
import { updateStudyTime } from "@/lib/progress";
import { useProgress } from "@/lib/useProgress";
import { topics } from "@/lib/validation";
import type { ExamId, Level } from "@/lib/types";
import { PROGRESS_STORAGE_KEY } from "@/lib/progress";
function download(text: string, filename: string) { const url = URL.createObjectURL(new Blob([text], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function SettingsClient() {
  const { progress, setProgress, resetProgress, importProgress, hydrated, canEdit, storageError, blocked } = useProgress();
  const [importText, setImportText] = useState(""); const [message, setMessage] = useState("");
  if (!hydrated) return <p>Загрузка настроек...</p>;
  function handleImport(text = importText) { try { importProgress(text); setMessage("Файл проверен и импортирован. Старый формат мигрирует автоматически."); setImportText(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Файл не прошел проверку. Текущие данные не изменены."); } }
  return <div className="space-y-5 pb-20"><section className="panel space-y-3"><h1 className="text-2xl font-semibold">Настройки</h1><p>Данные хранятся в этом браузере. Экспортируйте резервную копию перед сменой устройства или очисткой браузера.</p>{message && <p role="status">{message}</p>}{storageError && <p role="alert">{storageError}</p>}</section>
    <section className="panel space-y-4"><h2 className="text-lg font-semibold">Учебная цель</h2><label className="block">Экзамен<select className="field mt-2" value={progress.examId} disabled={!canEdit} onChange={(event) => setProgress((latest) => ({ ...latest, examId: event.target.value as ExamId }))}><option value="goethe-b1">Goethe-Zertifikat B1</option><option value="telc-b1">telc Deutsch B1</option></select></label><label className="block">Сложность новых материалов<select className="field mt-2" value={progress.targetLevel} disabled={!canEdit} onChange={(event) => setProgress((latest) => ({ ...latest, targetLevel: event.target.value as Level }))}><option value="A2">A2: укрепить основу</option><option value="B1">B1: подготовка к экзамену</option></select></label><p className="text-sm">Это выбранная сложность, а не измеренный уровень. Настройки применяются к новым занятиям; начатые сохраняют свои условия.</p><fieldset><legend className="font-medium">Темы новых занятий</legend><div className="mt-3 flex flex-wrap gap-3">{topics.map((topic) => <label key={topic} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={progress.preferredTopics.includes(topic)} disabled={!canEdit || (progress.preferredTopics.length === 1 && progress.preferredTopics.includes(topic))} onChange={(event) => { const checked = event.target.checked; setProgress((latest) => ({ ...latest, preferredTopics: checked ? [...new Set([...latest.preferredTopics, topic])] : latest.preferredTopics.filter((value) => value !== topic) })); }} />{topic}</label>)}</div></fieldset><label className="block">Время занятия<input type="time" className="field mt-2" value={progress.studyTime} disabled={!canEdit} onChange={(event) => { const value = event.target.value; if (value) setProgress((latest) => updateStudyTime(latest, value)); }} /></label><p className="text-sm">Ориентир для понедельника-пятницы. Автоматические уведомления не включены; выходные не обязательны.</p></section>
    <section className="panel space-y-4"><h2 className="text-lg font-semibold">Резервные копии</h2><div className="flex flex-wrap gap-3"><button className="button" onClick={() => download(JSON.stringify(progress, null, 2), "german-b1-progress-v2.json")}>Скачать текущий JSON</button><button className="button-secondary" onClick={() => { try { const raw = window.localStorage.getItem(PROGRESS_STORAGE_KEY); if (raw) download(raw, "german-b1-storage-original.json"); else setMessage("Сохраненного файла пока нет."); } catch { setMessage("Браузер не дает прочитать исходное хранилище."); } }}>Скачать исходное хранилище</button></div>{blocked && <p>Исходное хранилище содержит прежние данные, даже если они не прошли проверку. Скачайте его перед сбросом.</p>}<label className="block">Импорт файла<input type="file" accept=".json,application/json" className="field mt-2" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 10_000_000) { setMessage("Файл слишком большой."); return; } setImportText(await file.text()); event.target.value = ""; }} /></label><label className="block">Или вставьте JSON<textarea className="field mt-2 font-mono text-xs" value={importText} onChange={(event) => setImportText(event.target.value)} rows={6} /></label><p className="text-sm">Импорт заменит текущий прогресс после полной проверки файла.</p><button className="button-secondary" disabled={!importText.trim()} onClick={() => handleImport()}>Проверить и импортировать</button><details><summary>Текущий прогресс</summary><pre className="mt-3 max-h-80 overflow-auto rounded-md bg-paper p-3 text-xs">{JSON.stringify(progress, null, 2)}</pre></details></section>
    <section className="panel"><h2 className="font-semibold">Сброс</h2><p className="my-3 text-sm">Удаляет текущий локальный прогресс. Сначала скачайте резервную копию.</p><button className="button-secondary" onClick={() => { if (window.confirm("Удалить весь локальный прогресс? Сохраните резервную копию перед сбросом.")) { resetProgress(); setMessage("Создан новый прогресс."); } }}>Сбросить прогресс</button></section>
  </div>;
}
