"use client";
import { useRouter } from "next/navigation";
import { makePracticeLesson, skills, skillStatus, statusLabels } from "@/lib/curriculum";
import { saveGeneratedLesson } from "@/lib/progress";
import { nextLessonKind } from "@/lib/schedule";
import { useProgress } from "@/lib/useProgress";
export function SkillsClient() {
  const { progress, setProgress, hydrated, canEdit } = useProgress(); const router = useRouter();
  if (!hydrated) return <p>Загрузка навыков...</p>;
  return <div className="space-y-5 pb-20"><section className="panel space-y-3"><h1 className="text-2xl font-semibold">Навыки и история</h1><p>Начальная проверка охватывает грамматику, короткое чтение и письменную попытку. Общий уровень немецкого по ней не устанавливается.</p><button className="button-secondary" disabled={!canEdit} onClick={() => { setProgress((latest) => saveGeneratedLesson(latest, makePracticeLesson(latest, "word-order", new Date(), "diagnostic"))); router.push("/lesson"); }}>{progress.diagnosticCompletedAt ? "Повторить диагностику" : "Пройти диагностику"}</button></section>
    <p className="text-sm text-ink/65">«Получается» означает успешную первую попытку без подсказки. «Подтверждено спустя время» требует двух успешных наблюдений на разных заданиях с промежутком хотя бы 3 дня, после последней ошибки. Через 30 дней нужна новая проверка. Это правило тренажера, не сертификат B1. Письмо оценивается отдельно по сохраненной рубрике; упражнения на формулы письма не доказывают владение полным текстом.</p>
    <section className="grid gap-4 md:grid-cols-2">{skills.map((skill) => { const evidence = progress.skillEvidence[skill.id]; return <article className="panel space-y-3" key={skill.id}><h2 className="font-semibold">{skill.title}</h2><p>{skill.goal}</p><p className="text-sm text-lake">{statusLabels[skillStatus(progress, skill.id)]}</p><p className="text-xs">Наблюдений: {evidence.length}. Последнее: {evidence.at(-1)?.date ?? "нет"}.</p>{skill.prerequisites.length > 0 && <p className="text-xs">Основа: {skill.prerequisites.map((id) => skills.find((item) => item.id === id)?.title).join(", ")}.</p>}<button className="button-secondary" disabled={!canEdit} onClick={() => { setProgress((latest) => saveGeneratedLesson(latest, makePracticeLesson(latest, skill.id, new Date(), nextLessonKind(latest)))); router.push("/lesson"); }}>Отработать навык</button></article>; })}</section>
    <section className="panel space-y-3"><h2 className="text-lg font-semibold">Незавершенные занятия</h2>{Object.entries(progress.drafts).filter(([id]) => !progress.completedLessonIds.includes(id)).map(([id, draft]) => <div key={id} className="flex flex-wrap items-center justify-between gap-3 border-t border-ink/10 pt-3"><div><p>{progress.generatedLessons[id]?.title}</p><p className="text-xs">Изменено {new Date(draft.updatedAt).toLocaleString("ru-RU")}</p></div><button className="button-secondary" disabled={!canEdit} onClick={() => { setProgress((latest) => ({ ...latest, currentGeneratedLessonId: id })); router.push("/lesson"); }}>Продолжить черновик</button></div>)}</section>
    <section className="panel space-y-3"><h2 className="text-lg font-semibold">Последние выполненные занятия</h2>{progress.attempts.slice(-20).reverse().map((attempt, index) => <details key={attempt.id ?? index} className="border-t border-ink/10 pt-3"><summary>{attempt.title ?? attempt.lessonId} · {attempt.completedDate}</summary>{attempt.elapsedSeconds !== undefined && <p className="mt-2 text-sm">От начала до завершения: {Math.round(attempt.elapsedSeconds / 60)} минут, включая перерывы.</p>}<div className="mt-3 space-y-2">{Object.values(attempt.exerciseAnswers).map((answer, index) => <p key={index} lang="de" className="whitespace-pre-wrap rounded-md bg-paper p-3">{answer}</p>)}</div>{attempt.feedback?.rubric?.map((item) => <p key={item.criterion} className="mt-2 text-sm">{item.explanationRu} ({item.score}/3)</p>)}<button className="button-secondary mt-3" disabled={!canEdit} onClick={() => { setProgress((latest) => saveGeneratedLesson(latest, makePracticeLesson(latest, attempt.skillId ?? "writing", new Date(), nextLessonKind(latest)))); router.push("/lesson"); }}>Новая попытка на этот навык</button></details>)}{progress.attempts.length === 0 && <p>Выполненных занятий пока нет.</p>}</section>
  </div>;
}
